version: '3'
services:
  app:
    build:
      context: .
    tty: true
    volumes:
      - .:/app
    environment:
     - WATCHPACK_POLLING=true
    ports:
      - "1313:3000"
    command: sh -c "cd src && npm install && npm run dev"